### ISSUE TITLE
Content-Encoding header deletion

### ISSUE THREAD

**Issue by gmuder** [lautis/rack-inflater#2]
What is the reason you delete the header _Content-Encoding_ here?

https://github.com/lautis/rack-inflater/blob/master/lib/rack/inflater.rb#L19

**Comment by graudeejs** [comment]
I know it's been a while since the OP asked question, but here's my answer anyway:

Because body was modified, and is no longer gzip encoded.
Leaving header could have unpredictable bugs (some other middleware or endpoint might try to decompress already decompressed body, resulting in runtime exception).
